package com.halo.demo.model;

public class Game {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.gno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer gno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.gname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.winner
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer winner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.type
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer rankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.gurl
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String gurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Boolean isconfirmed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.gno
     *
     * @return the value of game.gno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getGno() {
        return gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.gno
     *
     * @param gno the value for game.gno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setGno(Integer gno) {
        this.gno = gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.gname
     *
     * @return the value of game.gname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.gname
     *
     * @param gname the value for game.gname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.winner
     *
     * @return the value of game.winner
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getWinner() {
        return winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.winner
     *
     * @param winner the value for game.winner
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setWinner(Integer winner) {
        this.winner = winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.type
     *
     * @return the value of game.type
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.type
     *
     * @param type the value for game.type
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.rank
     *
     * @return the value of game.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.rank
     *
     * @param rank the value for game.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.rankno
     *
     * @return the value of game.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getRankno() {
        return rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.rankno
     *
     * @param rankno the value for game.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRankno(Integer rankno) {
        this.rankno = rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.gurl
     *
     * @return the value of game.gurl
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getGurl() {
        return gurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.gurl
     *
     * @param gurl the value for game.gurl
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setGurl(String gurl) {
        this.gurl = gurl == null ? null : gurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.isconfirmed
     *
     * @return the value of game.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Boolean getIsconfirmed() {
        return isconfirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.isconfirmed
     *
     * @param isconfirmed the value for game.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setIsconfirmed(Boolean isconfirmed) {
        this.isconfirmed = isconfirmed;
    }
}