package com.halo.demo.model;

public class Paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.ppno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer ppno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.ppname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String ppname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.author
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.journal
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String journal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.pubdate
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Long pubdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer rankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.ppurl
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String ppurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Boolean isconfirmed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.ppno
     *
     * @return the value of paper.ppno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getPpno() {
        return ppno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.ppno
     *
     * @param ppno the value for paper.ppno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setPpno(Integer ppno) {
        this.ppno = ppno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.ppname
     *
     * @return the value of paper.ppname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getPpname() {
        return ppname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.ppname
     *
     * @param ppname the value for paper.ppname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setPpname(String ppname) {
        this.ppname = ppname == null ? null : ppname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.author
     *
     * @return the value of paper.author
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.author
     *
     * @param author the value for paper.author
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.journal
     *
     * @return the value of paper.journal
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getJournal() {
        return journal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.journal
     *
     * @param journal the value for paper.journal
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setJournal(String journal) {
        this.journal = journal == null ? null : journal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.pubdate
     *
     * @return the value of paper.pubdate
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Long getPubdate() {
        return pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.pubdate
     *
     * @param pubdate the value for paper.pubdate
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setPubdate(Long pubdate) {
        this.pubdate = pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.rank
     *
     * @return the value of paper.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.rank
     *
     * @param rank the value for paper.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.rankno
     *
     * @return the value of paper.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getRankno() {
        return rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.rankno
     *
     * @param rankno the value for paper.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRankno(Integer rankno) {
        this.rankno = rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.ppurl
     *
     * @return the value of paper.ppurl
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getPpurl() {
        return ppurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.ppurl
     *
     * @param ppurl the value for paper.ppurl
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setPpurl(String ppurl) {
        this.ppurl = ppurl == null ? null : ppurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.isconfirmed
     *
     * @return the value of paper.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Boolean getIsconfirmed() {
        return isconfirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.isconfirmed
     *
     * @param isconfirmed the value for paper.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setIsconfirmed(Boolean isconfirmed) {
        this.isconfirmed = isconfirmed;
    }
}