package com.halo.demo.model;

import java.util.ArrayList;
import java.util.List;

public class PaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public PaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPpnoIsNull() {
            addCriterion("ppno is null");
            return (Criteria) this;
        }

        public Criteria andPpnoIsNotNull() {
            addCriterion("ppno is not null");
            return (Criteria) this;
        }

        public Criteria andPpnoEqualTo(Integer value) {
            addCriterion("ppno =", value, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoNotEqualTo(Integer value) {
            addCriterion("ppno <>", value, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoGreaterThan(Integer value) {
            addCriterion("ppno >", value, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ppno >=", value, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoLessThan(Integer value) {
            addCriterion("ppno <", value, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoLessThanOrEqualTo(Integer value) {
            addCriterion("ppno <=", value, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoIn(List<Integer> values) {
            addCriterion("ppno in", values, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoNotIn(List<Integer> values) {
            addCriterion("ppno not in", values, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoBetween(Integer value1, Integer value2) {
            addCriterion("ppno between", value1, value2, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnoNotBetween(Integer value1, Integer value2) {
            addCriterion("ppno not between", value1, value2, "ppno");
            return (Criteria) this;
        }

        public Criteria andPpnameIsNull() {
            addCriterion("ppname is null");
            return (Criteria) this;
        }

        public Criteria andPpnameIsNotNull() {
            addCriterion("ppname is not null");
            return (Criteria) this;
        }

        public Criteria andPpnameEqualTo(String value) {
            addCriterion("ppname =", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameNotEqualTo(String value) {
            addCriterion("ppname <>", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameGreaterThan(String value) {
            addCriterion("ppname >", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameGreaterThanOrEqualTo(String value) {
            addCriterion("ppname >=", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameLessThan(String value) {
            addCriterion("ppname <", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameLessThanOrEqualTo(String value) {
            addCriterion("ppname <=", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameLike(String value) {
            addCriterion("ppname like", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameNotLike(String value) {
            addCriterion("ppname not like", value, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameIn(List<String> values) {
            addCriterion("ppname in", values, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameNotIn(List<String> values) {
            addCriterion("ppname not in", values, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameBetween(String value1, String value2) {
            addCriterion("ppname between", value1, value2, "ppname");
            return (Criteria) this;
        }

        public Criteria andPpnameNotBetween(String value1, String value2) {
            addCriterion("ppname not between", value1, value2, "ppname");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(Integer value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(Integer value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(Integer value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(Integer value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(Integer value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(Integer value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<Integer> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<Integer> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(Integer value1, Integer value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(Integer value1, Integer value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andJournalIsNull() {
            addCriterion("journal is null");
            return (Criteria) this;
        }

        public Criteria andJournalIsNotNull() {
            addCriterion("journal is not null");
            return (Criteria) this;
        }

        public Criteria andJournalEqualTo(String value) {
            addCriterion("journal =", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotEqualTo(String value) {
            addCriterion("journal <>", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThan(String value) {
            addCriterion("journal >", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThanOrEqualTo(String value) {
            addCriterion("journal >=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThan(String value) {
            addCriterion("journal <", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThanOrEqualTo(String value) {
            addCriterion("journal <=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLike(String value) {
            addCriterion("journal like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotLike(String value) {
            addCriterion("journal not like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalIn(List<String> values) {
            addCriterion("journal in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotIn(List<String> values) {
            addCriterion("journal not in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalBetween(String value1, String value2) {
            addCriterion("journal between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotBetween(String value1, String value2) {
            addCriterion("journal not between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andPubdateIsNull() {
            addCriterion("pubdate is null");
            return (Criteria) this;
        }

        public Criteria andPubdateIsNotNull() {
            addCriterion("pubdate is not null");
            return (Criteria) this;
        }

        public Criteria andPubdateEqualTo(Long value) {
            addCriterion("pubdate =", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateNotEqualTo(Long value) {
            addCriterion("pubdate <>", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateGreaterThan(Long value) {
            addCriterion("pubdate >", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateGreaterThanOrEqualTo(Long value) {
            addCriterion("pubdate >=", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateLessThan(Long value) {
            addCriterion("pubdate <", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateLessThanOrEqualTo(Long value) {
            addCriterion("pubdate <=", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateIn(List<Long> values) {
            addCriterion("pubdate in", values, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateNotIn(List<Long> values) {
            addCriterion("pubdate not in", values, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateBetween(Long value1, Long value2) {
            addCriterion("pubdate between", value1, value2, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateNotBetween(Long value1, Long value2) {
            addCriterion("pubdate not between", value1, value2, "pubdate");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(String value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(String value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(String value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(String value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(String value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(String value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLike(String value) {
            addCriterion("rank like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotLike(String value) {
            addCriterion("rank not like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<String> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<String> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(String value1, String value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(String value1, String value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRanknoIsNull() {
            addCriterion("rankno is null");
            return (Criteria) this;
        }

        public Criteria andRanknoIsNotNull() {
            addCriterion("rankno is not null");
            return (Criteria) this;
        }

        public Criteria andRanknoEqualTo(Integer value) {
            addCriterion("rankno =", value, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoNotEqualTo(Integer value) {
            addCriterion("rankno <>", value, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoGreaterThan(Integer value) {
            addCriterion("rankno >", value, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoGreaterThanOrEqualTo(Integer value) {
            addCriterion("rankno >=", value, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoLessThan(Integer value) {
            addCriterion("rankno <", value, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoLessThanOrEqualTo(Integer value) {
            addCriterion("rankno <=", value, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoIn(List<Integer> values) {
            addCriterion("rankno in", values, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoNotIn(List<Integer> values) {
            addCriterion("rankno not in", values, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoBetween(Integer value1, Integer value2) {
            addCriterion("rankno between", value1, value2, "rankno");
            return (Criteria) this;
        }

        public Criteria andRanknoNotBetween(Integer value1, Integer value2) {
            addCriterion("rankno not between", value1, value2, "rankno");
            return (Criteria) this;
        }

        public Criteria andPpurlIsNull() {
            addCriterion("ppurl is null");
            return (Criteria) this;
        }

        public Criteria andPpurlIsNotNull() {
            addCriterion("ppurl is not null");
            return (Criteria) this;
        }

        public Criteria andPpurlEqualTo(String value) {
            addCriterion("ppurl =", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlNotEqualTo(String value) {
            addCriterion("ppurl <>", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlGreaterThan(String value) {
            addCriterion("ppurl >", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlGreaterThanOrEqualTo(String value) {
            addCriterion("ppurl >=", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlLessThan(String value) {
            addCriterion("ppurl <", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlLessThanOrEqualTo(String value) {
            addCriterion("ppurl <=", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlLike(String value) {
            addCriterion("ppurl like", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlNotLike(String value) {
            addCriterion("ppurl not like", value, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlIn(List<String> values) {
            addCriterion("ppurl in", values, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlNotIn(List<String> values) {
            addCriterion("ppurl not in", values, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlBetween(String value1, String value2) {
            addCriterion("ppurl between", value1, value2, "ppurl");
            return (Criteria) this;
        }

        public Criteria andPpurlNotBetween(String value1, String value2) {
            addCriterion("ppurl not between", value1, value2, "ppurl");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedIsNull() {
            addCriterion("isconfirmed is null");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedIsNotNull() {
            addCriterion("isconfirmed is not null");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedEqualTo(Boolean value) {
            addCriterion("isconfirmed =", value, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedNotEqualTo(Boolean value) {
            addCriterion("isconfirmed <>", value, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedGreaterThan(Boolean value) {
            addCriterion("isconfirmed >", value, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isconfirmed >=", value, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedLessThan(Boolean value) {
            addCriterion("isconfirmed <", value, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedLessThanOrEqualTo(Boolean value) {
            addCriterion("isconfirmed <=", value, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedIn(List<Boolean> values) {
            addCriterion("isconfirmed in", values, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedNotIn(List<Boolean> values) {
            addCriterion("isconfirmed not in", values, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedBetween(Boolean value1, Boolean value2) {
            addCriterion("isconfirmed between", value1, value2, "isconfirmed");
            return (Criteria) this;
        }

        public Criteria andIsconfirmedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isconfirmed not between", value1, value2, "isconfirmed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 10 14:12:29 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated Tue Dec 10 14:12:29 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}