package com.halo.demo.model;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer pno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.manager
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer rankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Boolean isconfirmed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pno
     *
     * @return the value of project.pno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getPno() {
        return pno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pno
     *
     * @param pno the value for project.pno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setPno(Integer pno) {
        this.pno = pno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pname
     *
     * @return the value of project.pname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pname
     *
     * @param pname the value for project.pname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.manager
     *
     * @return the value of project.manager
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.manager
     *
     * @param manager the value for project.manager
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setManager(Integer manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.rank
     *
     * @return the value of project.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.rank
     *
     * @param rank the value for project.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.rankno
     *
     * @return the value of project.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getRankno() {
        return rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.rankno
     *
     * @param rankno the value for project.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRankno(Integer rankno) {
        this.rankno = rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.isconfirmed
     *
     * @return the value of project.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Boolean getIsconfirmed() {
        return isconfirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.isconfirmed
     *
     * @param isconfirmed the value for project.isconfirmed
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setIsconfirmed(Boolean isconfirmed) {
        this.isconfirmed = isconfirmed;
    }
}