package com.halo.demo.model;

public class Site {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer rankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.gain
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String gain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.type
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.proportion
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer proportion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.rankno
     *
     * @return the value of site.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getRankno() {
        return rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.rankno
     *
     * @param rankno the value for site.rankno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRankno(Integer rankno) {
        this.rankno = rankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.gain
     *
     * @return the value of site.gain
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getGain() {
        return gain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.gain
     *
     * @param gain the value for site.gain
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setGain(String gain) {
        this.gain = gain == null ? null : gain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.type
     *
     * @return the value of site.type
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.type
     *
     * @param type the value for site.type
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.rank
     *
     * @return the value of site.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.rank
     *
     * @param rank the value for site.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.proportion
     *
     * @return the value of site.proportion
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getProportion() {
        return proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.proportion
     *
     * @param proportion the value for site.proportion
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setProportion(Integer proportion) {
        this.proportion = proportion;
    }
}