package com.halo.demo.model;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.tno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.tname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.tpassword
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String tpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.age
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.email
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    private String rank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.tno
     *
     * @return the value of tuser.tno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.tno
     *
     * @param tno the value for tuser.tno
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.tname
     *
     * @return the value of tuser.tname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.tname
     *
     * @param tname the value for tuser.tname
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.tpassword
     *
     * @return the value of tuser.tpassword
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getTpassword() {
        return tpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.tpassword
     *
     * @param tpassword the value for tuser.tpassword
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword == null ? null : tpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.age
     *
     * @return the value of tuser.age
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.age
     *
     * @param age the value for tuser.age
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.email
     *
     * @return the value of tuser.email
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.email
     *
     * @param email the value for tuser.email
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.rank
     *
     * @return the value of tuser.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.rank
     *
     * @param rank the value for tuser.rank
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }
}