package com.halo.demo.mapper;

import com.halo.demo.model.Game;
import com.halo.demo.model.GameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    long countByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int deleteByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int deleteByPrimaryKey(Integer gno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int insertSelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    List<Game> selectByExampleWithRowbounds(GameExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    List<Game> selectByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    Game selectByPrimaryKey(Integer gno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") Game record, @Param("example") GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByExample(@Param("record") Game record, @Param("example") GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByPrimaryKeySelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbg.generated Tue Dec 10 16:22:30 CST 2019
     */
    int updateByPrimaryKey(Game record);
}